### ISSUE TITLE
Implement pipette tool

### ISSUE THREAD

**Issue by neothemachine** [Reading-eScience-Centre/leaflet-coverage#1]
The goal is to have some mouse and touch compatible UI workflow to find out the exact range value of a given point on the map. Since a simple click/touch is often overloaded with other actions it may be better to invoke this action separately similar to the pipette tool of drawing software. There would be a pipette button that the user has to click, then the mouse cursor would change into that pipette (or something similar like a cross), and then the user can click on arbitrary points on the map which would trigger an event in the legends which then would highlight the clicked value. When the pipette tool is clicked again (or ESC is pressed) the normal UI interaction is restored and the legends go back to their original state (removing the previously highlighted value).

**Comment by neothemachine** [comment]
Addition: When a mouse is used, then the legend updates could also happen continuously when hovering.

**Comment by jonblower** [comment]
Makes sense to me. The other kind of interaction we should think about is drawing polygons or lines on the map, and disambiguating these from drags or pinches. I guess the solution here again is to click a button to change the interaction mode.

I don't know if Barbara has looked into similar issues for her mapping applications.

**Comment by neothemachine** [comment]
This is implemented now in the form of a draggable popup.
