### ISSUE TITLE
Fix Safari bug

### ISSUE THREAD

**Issue by letmaik** [Reading-eScience-Centre/leaflet-coverage#5]
The playground (http://covjson.org/playground/) doesn't work for some examples on Safari. Should test that on a Mac and fix it.

**Comment by jonblower** [comment]
I wonder if Safari on PC would show the same issues (to save you tracking down a Mac)? If you let me know which ones I can test on my Mac.

**Comment by neothemachine** [comment]
I would test that but Safari on Windows doesn't exist anymore. No 
worries, I'll use Rileys Mac when I get a chance. Have to put a 
development version of the playground on it, as I can't see much from 
minified JS code..
